# release.toml （ルート直下）
# ---------------------------------
# workspace           = true          # ワークスペース全体を対象
consolidate-commits = true          # 1 コミットにまとめる
push-remote         = "origin"

tag-name            = "v{{version}}"
tag-message         = "Release {{crate_name}} v{{version}}"

pre-release-commit-message  = "chore(release): {{crate_name}} v{{version}}"
# CHANGELOG を git-cliff で生成してコミットに含める
pre-release-hook    = [
    "git cliff -o CHANGELOG.md --tag v{{version}}"
]

# crates.io への公開と同時に GitHub Release を作成
post-release-hook   = [
    "gh release create v{{version}} --notes-file CHANGELOG.md"
]
