# .github/workflows/release.yml
name: CI & Release
on:
  push:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - run: cargo test --workspace

  release:
    needs: test
    runs-on: ubuntu-latest
    permissions:
      contents: write      # タグ／Release 作成に必須
    steps:
      - uses: actions/checkout@v4
        with: { fetch-depth: 0 }
      - uses: dtolnay/rust-toolchain@stable
      # ★ pre-built バイナリを DL して ~/.cargo/bin へ展開
      - name: Install cargo-release
        uses: taiki-e/install-action@cargo-release      # v0.25.* など指定も可 :contentReference[oaicite:0]{index=0}
      - name: cargo-release
        # 手元で動かすのと同じ ― 自動で version bump → tag → push → publish
        run: |
          cargo release minor --execute --no-confirm
        env:
          CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}
